---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
    dash.ulagbulag.io/subject: mobilex-exp
spec:
  selector:
    matchLabels:
      app: backend
      dash.ulagbulag.io/subject: mobilex-exp
  template:
    metadata:
      labels:
        app: backend
        dash.ulagbulag.io/subject: mobilex-exp
    spec:
      containers:
        - name: server
          # TODO(user): change to your image
          image: docker.io/peter4885/mobilex_backend:v0.1
          env:
            - name: BASE_URL
              value: /api/v1
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai
                  key: OPENAI_API_KEY
                  optional: true
          ports:
            - name: http
              protocol: TCP
              containerPort: 8000
          volumeMounts:
            - name: huggingface-hub-token
              mountPath: /root/.cache/huggingface/token
              subPath: token
      volumes:
        - name: huggingface-hub-token
          secret:
            optional: true
            secretName: huggingface-hub
            items:
              - key: HUGGING_FACE_HUB_TOKEN
                path: token
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
    dash.ulagbulag.io/subject: mobilex-exp
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Secret
metadata:
  name: openai
stringData:
  # TODO(user): change your own token!
  OPENAI_API_KEY: "sk-proj-PtglPboxV8sfoeXqIWunT3BlbkFJTucatMfSe8XmxeWk4iET"